#!/usr/bin/env bash
# ============================================================================
# TempMail Platform — Universal One-Click Deploy Script
# ============================================================================
# Supported OS: Ubuntu, Debian, CentOS, RHEL, Fedora, Rocky, AlmaLinux,
#               Arch Linux, Alpine Linux
# Usage:
#   chmod +x deploy.sh && ./deploy.sh
# ============================================================================

set -euo pipefail

# Source shared library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib.sh"

# --- Parse flags ---
parse_flags "deploy.sh" "Full deployment of the TempMail platform (primary server)." "$@"

# --- Collect Configuration ---
collect_configuration() {
    log_step "Configuration"

    read -rp "$(echo -e "${CYAN}? Mail domain (e.g., mail.example.com): ${NC}")" MAIL_DOMAIN
    [[ -z "$MAIL_DOMAIN" ]] && log_error "Domain cannot be empty."

    read -rp "$(echo -e "${CYAN}? Frontend URL (e.g., https://app.example.com): ${NC}")" FRONTEND_URL

    echo -e "\n  ${YELLOW}Cloudflare R2 Storage${NC}"
    read -rp "$(echo -e "${CYAN}  > R2 Account ID: ${NC}")" R2_ACCOUNT_ID
    read -rp "$(echo -e "${CYAN}  > R2 Access Key ID: ${NC}")" R2_ACCESS_KEY_ID
    read -rsp "$(echo -e "${CYAN}  > R2 Secret Access Key: ${NC}")" R2_SECRET_ACCESS_KEY
    echo ""
    read -rp "$(echo -e "${CYAN}  > R2 Bucket Name [tempmail-archives]: ${NC}")" R2_BUCKET_NAME
    R2_BUCKET_NAME=${R2_BUCKET_NAME:-tempmail-archives}
}

# --- Generate security tokens ---
generate_secrets() {
    log_step "Security Tokens"

    POSTGRES_PASSWORD=$(generate_token 24)
    REDIS_PASSWORD=$(generate_token 24)
    INTERNAL_API_TOKEN=$(generate_token 32)
    EXTERNAL_API_KEY=$(generate_token 32)
    ADMIN_API_KEY=$(generate_token 32)
    ADMIN_PANEL_PATH=$(generate_token 16)

    log_success "Database & cache passwords generated."
    log_success "API and admin access tokens generated."
}

# --- Write .env ---
create_env_file() {
    log_step "Environment File"

    cat > .env << EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# TempMail Platform v${TEMPMAIL_VERSION}
# ========================================

# Database
POSTGRES_USER=tempmail
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=tempmail_db
DATABASE_URL=host=postgres user=tempmail password=${POSTGRES_PASSWORD} dbname=tempmail_db port=5432 sslmode=disable TimeZone=UTC

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

# Security Tokens
INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
EXTERNAL_API_KEY=${EXTERNAL_API_KEY}
ADMIN_API_KEY=${ADMIN_API_KEY}
ADMIN_PANEL_PATH=${ADMIN_PANEL_PATH}

# Cloudflare R2
R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
R2_BUCKET_NAME=${R2_BUCKET_NAME}

# Spam
RSPAMD_URL=http://rspamd:11333
RSPAMD_PASSWORD=
SPAM_REJECT_THRESHOLD=15

# Frontend
FRONTEND_URL=${FRONTEND_URL}

# Limits
MAX_MESSAGE_SIZE_MB=25
MAX_ATTACHMENTS=10
MAX_ATTACHMENT_SIZE_MB=10

# Logging
LOG_LEVEL=info
LOG_MAX_AGE_DAYS=14
LOG_MAX_SIZE_MB=100
LOG_MAX_BACKUPS=10
EOF

    log_success ".env file written."
}

# --- Build & Deploy ---
deploy_services() {
    log_step "Build & Deploy"

    $SUDO mkdir -p /opt/stacks

    log_info "Building containers (this may take a few minutes)..."
    $SUDO docker compose build --no-cache

    log_info "Starting all services..."
    $SUDO docker compose up -d

    log_success "All services are up and running."
}

# --- Print summary ---
print_summary() {
    local PUBLIC_IP
    PUBLIC_IP=$(get_public_ip)

    echo -e "\n${GREEN}${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}${BOLD}║           ✅  DEPLOYMENT COMPLETE                        ║${NC}"
    echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════════════╝${NC}"

    echo -e "\n${CYAN}${BOLD}── Services ──${NC}"
    echo -e "  API Server       ${GREEN}http://localhost:4000${NC}"
    echo -e "  SMTP Inbound     ${GREEN}${MAIL_DOMAIN}:25${NC}"
    echo -e "  Rspamd UI        ${GREEN}http://localhost:11334${NC}"

    echo -e "\n${CYAN}${BOLD}── Web App Integration ──${NC}"
    echo -e "  API_URL           ${GREEN}http://${PUBLIC_IP}:4000${NC}"
    echo -e "  API_KEY           ${GREEN}${EXTERNAL_API_KEY}${NC}"

    echo -e "\n${CYAN}${BOLD}── Admin Access ──${NC}"
    echo -e "  ADMIN_KEY         ${GREEN}${ADMIN_API_KEY}${NC}"
    echo -e "  ADMIN_PANEL       ${GREEN}http://${PUBLIC_IP}:4000/${ADMIN_PANEL_PATH}/${NC}"

    echo -e "\n${CYAN}${BOLD}── Container Management ──${NC}"
    echo -e "  Dockge UI         ${GREEN}http://${PUBLIC_IP}:5001${NC}"
    echo -e "  ${DIM}(Create an admin account on first visit)${NC}"

    echo -e "\n${YELLOW}${BOLD}── DNS Configuration Required ──${NC}"
    echo -e "  MX   ${MAIL_DOMAIN}  →  ${MAIL_DOMAIN}  ${DIM}(priority 10)${NC}"
    echo -e "  A    ${MAIL_DOMAIN}  →  ${PUBLIC_IP}"

    echo -e "\n${RED}${BOLD}  ⚠  Save these keys NOW — they will not be shown again!${NC}"
    print_elapsed
}

# --- Main ---
main() {
    print_banner "Primary Server — Full Deployment"
    check_root
    setup_os_prerequisites
    setup_docker
    setup_dockge
    collect_configuration
    generate_secrets
    create_env_file
    deploy_services
    print_summary
}

main
