#!/usr/bin/env bash
# ============================================================================
# TempMail Platform — One-Click Deploy Script
# ============================================================================
# Usage:
#   chmod +x deploy.sh
#   ./deploy.sh
# ============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║         TempMail Platform — One-Click Deploy            ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ---------------------------------------------------------------------------
# Helper: generate secure random token
# ---------------------------------------------------------------------------
generate_token() {
  openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | xxd -p | tr -d '\n'
}

# ---------------------------------------------------------------------------
# Step 1: Collect configuration
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[1/5] Configuration${NC}"

read -rp "Your domain (e.g., mail.example.com): " MAIL_DOMAIN
read -rp "Frontend URL (e.g., https://app.example.com): " FRONTEND_URL

echo ""
echo -e "${YELLOW}Cloudflare R2 Configuration:${NC}"
read -rp "  R2 Account ID: " R2_ACCOUNT_ID
read -rp "  R2 Access Key ID: " R2_ACCESS_KEY_ID
read -rsp "  R2 Secret Access Key: " R2_SECRET_ACCESS_KEY
echo ""
read -rp "  R2 Bucket Name [tempmail-archives]: " R2_BUCKET_NAME
R2_BUCKET_NAME=${R2_BUCKET_NAME:-tempmail-archives}

# ---------------------------------------------------------------------------
# Step 2: Generate secure tokens
# ---------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}[2/5] Generating secure tokens...${NC}"

POSTGRES_PASSWORD=$(generate_token 24)
REDIS_PASSWORD=$(generate_token 24)
INTERNAL_API_TOKEN=$(generate_token 32)
EXTERNAL_API_KEY=$(generate_token 32)
ADMIN_API_KEY=$(generate_token 32)
ADMIN_PANEL_PATH=$(generate_token 16)

echo -e "  ${GREEN}✓${NC} PostgreSQL password generated"
echo -e "  ${GREEN}✓${NC} Redis password generated"
echo -e "  ${GREEN}✓${NC} Internal API token generated"
echo -e "  ${GREEN}✓${NC} External API key generated"
echo -e "  ${GREEN}✓${NC} Admin API key generated"
echo -e "  ${GREEN}✓${NC} Admin panel secret path generated"

# ---------------------------------------------------------------------------
# Step 3: Write .env file
# ---------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}[3/5] Writing .env file...${NC}"

cat > .env << EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ========================================

# Database
POSTGRES_USER=tempmail
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=tempmail_db
DATABASE_URL=host=postgres user=tempmail password=${POSTGRES_PASSWORD} dbname=tempmail_db port=5432 sslmode=disable TimeZone=UTC

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

# Security Tokens
INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
EXTERNAL_API_KEY=${EXTERNAL_API_KEY}
ADMIN_API_KEY=${ADMIN_API_KEY}
ADMIN_PANEL_PATH=${ADMIN_PANEL_PATH}

# Cloudflare R2
R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
R2_BUCKET_NAME=${R2_BUCKET_NAME}

# Spam
RSPAMD_URL=http://rspamd:11333
RSPAMD_PASSWORD=
SPAM_REJECT_THRESHOLD=15

# Frontend (optional — only needed if browsers call API directly)
# FRONTEND_URL=${FRONTEND_URL}

# Limits
MAX_MESSAGE_SIZE_MB=25
MAX_ATTACHMENTS=10
MAX_ATTACHMENT_SIZE_MB=10

# Logging
LOG_LEVEL=info
LOG_MAX_AGE_DAYS=14
LOG_MAX_SIZE_MB=100
LOG_MAX_BACKUPS=10
EOF

echo -e "  ${GREEN}✓${NC} .env written"

# ---------------------------------------------------------------------------
# Step 4: Build & Deploy
# ---------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}[4/5] Building containers (multi-stage Go builds)...${NC}"
docker compose build --no-cache

echo ""
echo -e "${YELLOW}[5/5] Starting services...${NC}"
docker compose up -d

# ---------------------------------------------------------------------------
# Step 5: Print summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║            ✅ DEPLOYMENT COMPLETE                       ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}=== Connection Details ===${NC}"
echo ""
echo -e "  API URL:           ${GREEN}http://localhost:4000${NC}"
echo -e "  SMTP Inbound:      ${GREEN}${MAIL_DOMAIN}:25${NC}"
echo -e "  Rspamd UI:         ${GREEN}http://localhost:11334${NC}"
echo ""
echo -e "${CYAN}=== Web App Integration (Copy these 2 values) ===${NC}"
echo ""
echo -e "  API_URL:           ${GREEN}http://YOUR_SERVER_IP:4000${NC}"
echo -e "  API_KEY:           ${GREEN}${EXTERNAL_API_KEY}${NC}"
echo ""
echo -e "${CYAN}=== Admin Access ===${NC}"
echo ""
echo -e "  ADMIN_KEY:         ${GREEN}${ADMIN_API_KEY}${NC}"
echo -e "  ADMIN_PANEL_URL:   ${GREEN}http://localhost:4000/${ADMIN_PANEL_PATH}/${NC}"
echo ""
echo -e "${YELLOW}=== DNS CONFIGURATION REQUIRED ===${NC}"
echo ""
echo -e "  Add these DNS records for ${MAIL_DOMAIN}:"
echo -e "    MX   ${MAIL_DOMAIN}  →  ${MAIL_DOMAIN}  (priority 10)"
echo -e "    A    ${MAIL_DOMAIN}  →  YOUR_SERVER_IP"
echo ""
echo -e "${RED}⚠ Save these keys securely! They will NOT be shown again.${NC}"
echo ""
