package main

import (
	"bufio"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"net"
	gonet "net/http"
	"os"
	"os/signal"
	"path/filepath"
	"runtime"
	"strings"
	"syscall"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/limiter"
	fiberLogger "github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/google/uuid"
	"go.uber.org/zap"
	"tempmail/api/handlers"
	"tempmail/shared/config"
	"tempmail/shared/db"
	"tempmail/shared/logger"
	"tempmail/shared/models"
	"time"
)

// Cached at startup — avoid os.Getenv() on every admin request
var cachedAdminAPIKey string

func main() {
	// Load configuration from environment variables
	cfg := config.Load()

	if err := logger.InitLogger("api"); err != nil {
		log.Fatalf("Failed to initialize logger: %v", err)
	}
	defer logger.Log.Sync()

	// Initialize databases
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		logger.Log.Fatal("DATABASE_URL environment variable is required")
	}

	if err := db.InitPostgres(dbURL); err != nil {
		logger.Log.Fatal("Failed to initialize PostgreSQL", zap.Error(err))
	}

	redisURL := os.Getenv("REDIS_URL")
	if redisURL == "" {
		logger.Log.Fatal("REDIS_URL environment variable is required")
	}
	if err := db.InitRedis(redisURL); err != nil {
		logger.Log.Fatal("Failed to initialize Redis", zap.Error(err))
	}

	// AutoMigrate
	if err := models.Migrate(db.DB); err != nil {
		logger.Log.Fatal("Failed to migrate database", zap.Error(err))
	}

	// Auto-register this server as primary node
	autoRegisterPrimaryNode()

	// Preload default settings for Webhook, TTL, Rate Limit
	preloadDefaultSettings()

	// Sync API keys from DB to Redis + auto-generate if none exist
	handlers.SyncAPIKeysToRedis()
	autoGenerateDefaultAPIKey()

	// Cache admin key at startup
	cachedAdminAPIKey = os.Getenv("ADMIN_API_KEY")

	app := fiber.New(fiber.Config{
		BodyLimit:             cfg.API.BodyLimitBytes(),
		Concurrency:           cfg.API.Concurrency,
		ReadTimeout:           cfg.API.ReadTimeout,
		WriteTimeout:          cfg.API.WriteTimeout,
		IdleTimeout:           cfg.API.IdleTimeout,
		DisableStartupMessage: true,
		ServerHeader:          "",
		AppName:               "",
		ReadBufferSize:        8192,  // 8KB — reduces syscalls vs default 4KB
		WriteBufferSize:       8192,
	})

	// Startup resource banner — essential for debugging in production
	logger.Log.Info("🚀 TempMail API starting",
		zap.Int("cpus", runtime.NumCPU()),
		zap.Int("gomaxprocs", runtime.GOMAXPROCS(0)),
		zap.String("go_version", runtime.Version()),
		zap.Int("fiber_concurrency", cfg.API.Concurrency),
		zap.Int("db_max_open", cfg.DB.MaxOpenConns),
		zap.Int("db_max_idle", cfg.DB.MaxIdleConns),
		zap.Int("redis_pool", cfg.Redis.PoolSize),
		zap.String("read_timeout", cfg.API.ReadTimeout.String()),
		zap.String("write_timeout", cfg.API.WriteTimeout.String()),
		zap.String("idle_timeout", cfg.API.IdleTimeout.String()),
	)

	// -----------------------------------------------------------------------
	// GLOBAL MIDDLEWARES
	// -----------------------------------------------------------------------

	// Panic recovery
	app.Use(recover.New())

	// Request ID for audit trails
	app.Use(requestid.New())

	// Access logging
	app.Use(fiberLogger.New(fiberLogger.Config{
		Format:     "${time} | ${status} | ${latency} | ${ip} | ${method} ${path} | ${reqHeader:X-Request-Id}\n",
		TimeFormat: "2006-01-02 15:04:05",
	}))

	// Security headers
	app.Use(func(c *fiber.Ctx) error {
		c.Set("X-Content-Type-Options", "nosniff")
		c.Set("X-Frame-Options", "DENY")
		c.Set("X-XSS-Protection", "1; mode=block")
		c.Set("Referrer-Policy", "strict-origin-when-cross-origin")
		c.Set("Content-Security-Policy", "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: http:; font-src 'self' data: https://fonts.gstatic.com https://fonts.googleapis.com; connect-src 'self'; frame-src 'self'")
		c.Set("Strict-Transport-Security", "max-age=63072000; includeSubDomains")
		return c.Next()
	})

	// CORS — optional, only enabled when FRONTEND_URL is set.
	frontendURL := os.Getenv("FRONTEND_URL")
	if frontendURL != "" {
		app.Use(cors.New(cors.Config{
			AllowOrigins:     frontendURL,
			AllowMethods:     "GET,POST,PUT,DELETE,OPTIONS",
			AllowHeaders:     "Origin,Content-Type,Accept,Authorization,X-API-Key,X-Request-Id",
			AllowCredentials: true,
			MaxAge:           3600,
		}))
		logger.Log.Info("CORS enabled", zap.String("origins", frontendURL))
	}

	// -----------------------------------------------------------------------
	// PUBLIC ROUTES (rate limited per IP — open to the world)
	// -----------------------------------------------------------------------
	publicLimiter := limiter.New(limiter.Config{
		Max:        cfg.API.PublicRateLimitPerMin,
		Expiration: 1 * time.Minute,
		KeyGenerator: func(c *fiber.Ctx) string {
			return c.IP()
		},
		LimitReached: func(c *fiber.Ctx) error {
			logger.Log.Warn("Rate limit exceeded", zap.String("ip", c.IP()))
			return c.Status(fiber.StatusTooManyRequests).JSON(fiber.Map{
				"error": "Rate limit exceeded. Try again later.",
			})
		},
	})

	app.Get("/health", publicLimiter, func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})

	// Public: server info for DNS setup instructions (Web App uses this)
	app.Get("/api/server-info", publicLimiter, handlers.HandleServerInfo)

	// -----------------------------------------------------------------------
	// INTERNAL ROUTES — mail-edge → api (Bearer API_TOKEN)
	// -----------------------------------------------------------------------
	internal := app.Group("/internal")
	internal.Use(apiTokenMiddleware)
	internal.Post("/mail/ingest", handlers.HandleMailIngest)

	// -----------------------------------------------------------------------
	// SDK ROUTES — frontend → api (X-API-Key or Bearer API_TOKEN)
	// -----------------------------------------------------------------------
	v1 := app.Group("/v1")
	v1.Use(apiTokenMiddleware)
	v1.Post("/mailbox/create", handlers.HandleCreateMailbox)
	v1.Get("/mailbox/count", handlers.HandleMailboxCount)
	v1.Get("/mailbox/:id", handlers.HandleGetMailbox)
	v1.Get("/mailbox/:id/messages", handlers.HandleGetMessages)
	v1.Patch("/mailbox/:id", handlers.HandlePatchMailbox)
	v1.Delete("/mailbox/:id", handlers.HandleDeleteMailbox)
	v1.Get("/message/:id", handlers.HandleGetMessage)
	v1.Delete("/message/:id", handlers.HandleDeleteMessage)
	v1.Get("/attachment/:id", handlers.HandleDownloadAttachment)
	v1.Get("/domains", handlers.HandleListDomains)

	// -----------------------------------------------------------------------
	// ADMIN ROUTES
	// -----------------------------------------------------------------------

	// Login-specific limiter — strict to prevent brute-force
	loginLimiter := limiter.New(limiter.Config{
		Max:        cfg.API.LoginRateLimitPerMin,
		Expiration: 1 * time.Minute,
		KeyGenerator: func(c *fiber.Ctx) string {
			return c.IP()
		},
		LimitReached: func(c *fiber.Ctx) error {
			logger.Log.Warn("Login rate limit exceeded", zap.String("ip", c.IP()))
			return c.Status(fiber.StatusTooManyRequests).JSON(fiber.Map{
				"error": "Too many login attempts. Try again later.",
			})
		},
	})

	admin := app.Group("/admin")

	// Login route — public (no auth), strict rate limit
	admin.Post("/login", loginLimiter, handlers.HandleAdminLogin)

	// Protected admin routes — require Bearer session token
	admin.Use(adminAuthMiddleware)
	admin.Get("/dashboard", handlers.HandleAdminDashboard)
	admin.Get("/metrics", handlers.HandleAdminMetrics)

	// Domains CRUD
	admin.Get("/domains", handlers.HandleAdminDomains)
	admin.Get("/domains/dns-check", handlers.HandleDNSCheck)
	admin.Post("/domains", handlers.HandleAdminCreateDomain)
	admin.Put("/domains/:id", handlers.HandleAdminUpdateDomain)
	admin.Delete("/domains/:id", handlers.HandleAdminDeleteDomain)

	// Nodes CRUD
	admin.Get("/nodes", handlers.HandleAdminNodes)
	admin.Post("/nodes", handlers.HandleAdminCreateNode)
	admin.Put("/nodes/:id", handlers.HandleAdminUpdateNode)
	admin.Delete("/nodes/:id", handlers.HandleAdminDeleteNode)
	admin.Post("/nodes/:id/detect-hostname", handlers.HandleDetectHostname)

	// Filters CRUD
	admin.Get("/filters", handlers.HandleAdminFilters)
	admin.Post("/filters", handlers.HandleAdminCreateFilter)
	admin.Put("/filters/:id", handlers.HandleAdminUpdateFilter)
	admin.Delete("/filters/:id", handlers.HandleAdminDeleteFilter)

	// Mailboxes
	admin.Get("/mailboxes", handlers.HandleAdminMailboxes)
	admin.Post("/mailboxes/quick-create", handlers.HandleAdminQuickCreateMailbox)
	admin.Delete("/mailboxes/:id", handlers.HandleAdminDeleteMailbox)

	// Messages
	admin.Get("/messages", handlers.HandleAdminMessages)
	admin.Get("/messages/:id", handlers.HandleAdminMessageDetail)
	admin.Delete("/messages/:id", handlers.HandleAdminDeleteMessage)
	admin.Post("/messages/bulk-delete", handlers.HandleAdminBulkDeleteMessages)
	admin.Get("/attachment/:id", handlers.HandleDownloadAttachment)

	// Settings + Export/Import
	admin.Get("/settings", handlers.HandleAdminGetSettings)
	admin.Post("/settings", handlers.HandleAdminUpdateSettings)
	admin.Get("/export", handlers.HandleAdminExport)
	admin.Post("/import", handlers.HandleAdminImport)

	// API Keys CRUD
	admin.Get("/api-keys", handlers.HandleAdminAPIKeys)
	admin.Post("/api-keys", handlers.HandleAdminCreateAPIKey)
	admin.Put("/api-keys/:id", handlers.HandleAdminUpdateAPIKey)
	admin.Delete("/api-keys/:id", handlers.HandleAdminDeleteAPIKey)
	admin.Post("/api-keys/:id/roll", handlers.HandleAdminRollAPIKey)

	// Audit + Webhook
	admin.Get("/audit-log", handlers.HandleAdminAuditLog)
	admin.Post("/webhook-test", handlers.HandleAdminWebhookTest)

	// SSE — real-time events for admin panel (no polling)
	// Auth handled by adminAuthMiddleware (supports query param ?token= for EventSource)
	admin.Get("/events", func(c *fiber.Ctx) error {
		c.Set("Content-Type", "text/event-stream")
		c.Set("Cache-Control", "no-cache")
		c.Set("Connection", "keep-alive")
		c.Set("X-Accel-Buffering", "no")

		sub := db.Redis.Subscribe(context.Background(), "mail:events")
		ch := sub.Channel()

		c.Context().SetBodyStreamWriter(func(w *bufio.Writer) {
			defer sub.Close()

			// Send initial keepalive
			if _, err := fmt.Fprintf(w, ": connected\n\n"); err != nil {
				return
			}
			if err := w.Flush(); err != nil {
				return
			}

			ticker := time.NewTicker(12 * time.Second)
			defer ticker.Stop()

			for {
				select {
				case <-c.Context().Done():
					return
				case msg, ok := <-ch:
					if !ok {
						return
					}
					if _, err := fmt.Fprintf(w, "event: %s\ndata: {}\n\n", msg.Payload); err != nil {
						return
					}
					if err := w.Flush(); err != nil {
						return
					}
				case <-ticker.C:
					if _, err := fmt.Fprintf(w, ": keepalive\n\n"); err != nil {
						return
					}
					if err := w.Flush(); err != nil {
						return
					}
				}
			}
		})
		return nil
	})

	port := cfg.API.Port

	// Serve admin UI at a fixed path from .env
	adminPanelPath := os.Getenv("ADMIN_PANEL_PATH")
	if adminPanelPath == "" {
		logger.Log.Warn("ADMIN_PANEL_PATH not set — admin UI disabled. Set it in .env for a fixed, shareable path.")
	} else {
		app.Get("/"+adminPanelPath, func(c *fiber.Ctx) error {
			return c.SendFile("./admin-ui/index.html")
		})
		app.Get("/"+adminPanelPath+"/*", func(c *fiber.Ctx) error {
			file := c.Params("*")
			if file == "" {
				file = "index.html"
			}
			// Prevent path traversal — resolve and verify the path stays inside admin-ui/
			cleaned := filepath.Clean(filepath.Join("admin-ui", file))
			if !strings.HasPrefix(cleaned, "admin-ui"+string(filepath.Separator)) && cleaned != "admin-ui" {
				return c.Status(403).JSON(fiber.Map{"error": "forbidden"})
			}
			return c.SendFile("./" + cleaned)
		})
		logger.Log.Info("Admin panel available",
			zap.String("url", "http://localhost:"+port+"/"+adminPanelPath+"/"),
		)
	}

	// ---------------------------------------------------------------------------
	// GRACEFUL SHUTDOWN — drain in-flight requests before stopping
	// ---------------------------------------------------------------------------
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		logger.Log.Info("Starting API server", zap.String("port", port))
		if err := app.Listen(":" + port); err != nil {
			logger.Log.Fatal("API server failed", zap.Error(err))
		}
	}()

	<-quit
	logger.Log.Info("Shutting down gracefully (10s timeout)...")
	if err := app.ShutdownWithTimeout(10 * time.Second); err != nil {
		logger.Log.Error("Forced shutdown", zap.Error(err))
	}
	logger.Log.Info("Server stopped")
}

// ---------------------------------------------------------------------------
// AUTO-REGISTER PRIMARY NODE
// ---------------------------------------------------------------------------

func autoRegisterPrimaryNode() {
	var count int64
	db.DB.Model(&models.MailNode{}).Count(&count)
	if count > 0 {
		return // Nodes already exist, skip auto-registration
	}

	// Auto-detect public IP — no env vars needed
	ip := detectPublicIP()
	if ip == "" {
		logger.Log.Warn("Could not detect public IP — skipping auto-register primary node")
		return
	}

	// Try reverse DNS to auto-detect hostname
	hostname := detectHostname(ip)

	node := models.MailNode{
		ID:        uuid.New().String(),
		Name:      "primary",
		Hostname:  hostname,
		IPAddress: ip,
		Region:    "",
		Status:    "ACTIVE",
	}

	if err := db.DB.Create(&node).Error; err != nil {
		logger.Log.Warn("Failed to auto-register primary node", zap.Error(err))
		return
	}

	if hostname != "" {
		logger.Log.Info("Primary node auto-registered (hostname detected via PTR)",
			zap.String("name", node.Name),
			zap.String("hostname", hostname),
			zap.String("ip", ip),
		)
	} else {
		logger.Log.Info("Primary node auto-registered (no PTR record — set hostname in Admin Panel)",
			zap.String("name", node.Name),
			zap.String("ip", ip),
		)
	}
}

func detectPublicIP() string {
	// Try these services in order
	services := []string{
		"https://api.ipify.org",
		"https://ifconfig.me/ip",
		"https://icanhazip.com",
	}
	client := &gonet.Client{Timeout: 5 * time.Second}
	for _, url := range services {
		resp, err := client.Get(url)
		if err != nil {
			continue
		}
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		ip := strings.TrimSpace(string(body))
		if ip != "" {
			return ip
		}
	}
	return ""
}

// detectHostname does reverse DNS (PTR) lookup on an IP to find hostname.
// Returns empty string if no PTR record found.
func detectHostname(ip string) string {
	hosts, err := net.LookupAddr(ip)
	if err != nil || len(hosts) == 0 {
		return ""
	}
	// PTR records end with a dot — trim it
	h := strings.TrimSuffix(hosts[0], ".")
	// Skip generic ISP/cloud hostnames (they're not useful for MX)
	if strings.Contains(h, "compute") || strings.Contains(h, "bc.googleusercontent") {
		return ""
	}
	return h
}

// ---------------------------------------------------------------------------
// PRELOAD DEFAULT SETTINGS
// ---------------------------------------------------------------------------

func preloadDefaultSettings() {
	ctx := context.Background()
	defaults := map[string]string{
		// ── Webhook (notify frontend when mail arrives) ──
		"webhook_url":                "",     // URL to POST on new mail
		"webhook_secret":             "",     // HMAC secret for webhook

		// ── TTL / Cleanup (backend's job) ──
		"default_mailbox_ttl_hours":  "24",   // Mailbox auto-expire
		"default_message_ttl_hours":  "24",   // Message auto-delete
		"cleanup_interval_minutes":   "5",    // Worker cleanup interval

		// ── SMTP Limits (mail-edge needs these) ──
		"max_message_size_mb":        "25",   // Max email size
		"max_attachments":            "10",   // Max attachments per email
		"max_attachment_size_mb":     "10",   // Max single attachment size
		"spam_reject_threshold":      "15",   // Spam score to reject

		// ── Access Control ──
		"max_mailboxes_free":         "5",    // Max mailboxes per free tenant
		"allow_anonymous":            "true", // Allow anonymous mailbox creation
	}

	for k, v := range defaults {
		db.Redis.HSetNX(ctx, "system:settings", k, v)
	}

	logger.Log.Info("Default settings preloaded", zap.Int("keys", len(defaults)))
}

// ---------------------------------------------------------------------------
// AUTO-GENERATE DEFAULT API KEY
// ---------------------------------------------------------------------------

func autoGenerateDefaultAPIKey() {
	var count int64
	db.DB.Model(&models.APIKey{}).Where("status = ?", "ACTIVE").Count(&count)
	if count > 0 {
		return // Keys already exist
	}

	// Generate a default key
	rawKey := uuid.New().String() + "-" + uuid.New().String()
	hash := sha256.Sum256([]byte(rawKey))
	keyHash := fmt.Sprintf("%x", hash[:])

	apiKey := models.APIKey{
		ID:          uuid.New().String(),
		Name:        "default",
		KeyHash:     keyHash,
		KeyPrefix:   rawKey[:8],
		Permissions: "read,write",
		RateLimit:   100,
		Status:      "ACTIVE",
	}

	if err := db.DB.Create(&apiKey).Error; err != nil {
		logger.Log.Error("Failed to create default API key", zap.Error(err))
		return
	}

	handlers.SyncAPIKeysToRedis()

	// Store raw key in Redis for mail-edge to use as Bearer token
	db.Redis.Set(context.Background(), "system:api_token", rawKey, 0)

	logger.Log.Info("═══════════════════════════════════════════════════════")
	logger.Log.Info("DEFAULT API KEY GENERATED (save this — shown only once!)")
	logger.Log.Info("API_KEY: " + rawKey)
	logger.Log.Info("═══════════════════════════════════════════════════════")
}

// ---------------------------------------------------------------------------
// AUTH MIDDLEWARES
// ---------------------------------------------------------------------------

// apiTokenMiddleware validates API key against Redis (synced from DB)
// Accepts: X-API-Key: <raw_key>  OR  Authorization: Bearer <raw_key>
func apiTokenMiddleware(c *fiber.Ctx) error {
	// Extract token from either header
	token := c.Get("X-API-Key")
	if token == "" {
		auth := c.Get("Authorization")
		if strings.HasPrefix(auth, "Bearer ") {
			token = auth[7:]
		}
	}

	if token == "" {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"error": "API key required",
		})
	}

	// Hash the incoming key and check against Redis set
	// Optimized: hex.EncodeToString avoids fmt.Sprintf allocation
	hash := sha256.Sum256([]byte(token))
	keyHash := hex.EncodeToString(hash[:])

	ctx := context.Background()
	isMember, err := db.Redis.SIsMember(ctx, "system:api_key_hashes", keyHash).Result()
	if err != nil || !isMember {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"error": "Invalid API key",
		})
	}

	// Check if this key has internal (rate-limit bypass) flag
	meta, _ := db.Redis.HGet(ctx, "system:api_key_meta", keyHash).Result()
	if meta == "internal" {
		c.Locals("is_internal_key", true)
	}

	return c.Next()
}

// adminAuthMiddleware validates session token (Bearer header or ?token= query param) for admin panel access
func adminAuthMiddleware(c *fiber.Ctx) error {
	if cachedAdminAPIKey == "" {
		logger.Log.Error("ADMIN_API_KEY not configured — rejecting admin requests")
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": "Admin panel not configured",
		})
	}

	var token string

	// 1) Check Authorization: Bearer <token>
	auth := c.Get("Authorization")
	if strings.HasPrefix(auth, "Bearer ") {
		token = auth[7:] // faster than TrimPrefix
	}

	// 2) Fallback: ?token= query param (for EventSource/SSE which can't send headers)
	if token == "" {
		token = c.Query("token")
	}

	if token != "" {
		if username, ok := handlers.ValidateSessionToken(token, cachedAdminAPIKey); ok {
			c.Locals("admin_user", username)
			return c.Next()
		}
	}

	return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
		"error": "Invalid or expired session",
	})
}

func generateSecureToken(length int) string {
	b := make([]byte, length)
	rand.Read(b)
	return hex.EncodeToString(b)
}
